overblog_graphql:
    definitions:
        schema:
            query: Query
            mutation: Mutation
        mappings:
            types:
                -
                    types: [yaml]
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: ~
